/**
 * services/proxy/ai-commentary.ts — Vercel Edge Function
 *
 * POST /api/ai-commentary
 *
 * Accepts wave scenario context from the mobile client and returns a natural
 * language interpretation generated by claude-sonnet-4-20250514.
 *
 * The ANTHROPIC_API_KEY environment variable is server-side only — never
 * exposed in the client bundle.
 *
 * Request body:
 *   { ticker, waveLabel, structure, probability, fibLevels, regime,
 *     nextTarget, t2, t3, invalidation, price, gexLevel,
 *     altWaveLabel, altConfidence, waveType, waveStart,
 *     ewMode, htfLabel, htfTF, htfStructure }
 *
 * Response:
 *   { commentary: string }
 */

export const config = { runtime: 'edge' };

interface CommentaryRequest {
  ticker:        string;
  waveLabel:     string;
  structure:     string;
  probability:   number;
  fibLevels?:    { label: string; price: number }[];
  regime?:       string;
  nextTarget?:   number | null;
  t2?:           number | null;
  t3?:           number | null;
  invalidation?: number | null;
  price?:        number | null;
  gexLevel?:     string | null;
  altWaveLabel?: string | null;
  altConfidence?: number | null;
  waveType?:     string | null;   // 'impulse' | 'corrective' | 'forming_w3' etc.
  waveStart?:    number | null;   // price where current wave began
  ewMode?:       string | null;   // 'now' | 'multi-degree' | 'history'
  htfLabel?:     string | null;   // HTF current wave label (e.g. '3')
  htfTF?:        string | null;   // HTF timeframe (e.g. '1D')
  htfStructure?: string | null;   // HTF wave structure type
}

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }

  const apiKey = process.env['ANTHROPIC_API_KEY'];
  if (!apiKey) {
    return new Response(JSON.stringify({ error: 'AI commentary not configured' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  let body: CommentaryRequest;
  try {
    body = await req.json() as CommentaryRequest;
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  const {
    ticker, waveLabel, structure, probability,
    fibLevels, regime, nextTarget, t2, t3, invalidation, price, gexLevel,
    altWaveLabel, altConfidence, waveType, waveStart,
    ewMode, htfLabel, htfTF, htfStructure,
  } = body;

  const fibText = fibLevels && fibLevels.length > 0
    ? fibLevels.slice(0, 4).map((f) => `${f.label} at $${f.price.toFixed(2)}`).join(', ')
    : 'none computed';

  const targetsText = [
    nextTarget ? `T1 $${nextTarget.toFixed(2)}` : null,
    t2 ? `T2 $${t2.toFixed(2)}` : null,
    t3 ? `T3 $${t3.toFixed(2)}` : null,
  ].filter(Boolean).join(' → ') || 'none computed';

  const altText = altWaveLabel && altConfidence
    ? `Alternate scenario: Wave ${altWaveLabel} at ${Math.round(altConfidence * 100)}% probability`
    : null;

  const waveMoveText = waveStart && price
    ? `(moved ${((price - waveStart) / waveStart * 100).toFixed(1)}% from wave start $${waveStart.toFixed(2)})`
    : '';

  const isMultiDegree = ewMode === 'multi-degree' && htfLabel && htfTF;
  const htfContext = isMultiDegree
    ? `- Higher timeframe context: ${htfTF} Wave ${htfLabel} (${htfStructure ?? 'impulse'}) — current ${waveLabel} is a sub-wave of this larger structure`
    : null;

  // Wave stage: early (1/A), middle (2/3/B), late (4/5/C)
  const lateLabels  = ['4', '5', 'C'];
  const earlyLabels = ['1', '2', 'A'];
  const isLateStage  = lateLabels.includes(waveLabel);
  const isEarlyStage = earlyLabels.includes(waveLabel);
  const stageNote = isLateStage
    ? 'LATE STAGE — this wave is nearing completion; reversal risk is elevated.'
    : isEarlyStage
    ? 'EARLY STAGE — trend is establishing; follow-through probability is high.'
    : 'MID STAGE — strongest trending phase typically underway.';

  // Corrective bounce flag: W4, corrective B, or corrective structure in late position
  const expectingBounce = waveLabel === '4' || waveLabel === 'B'
    || (isLateStage && structure?.toLowerCase().includes('corrective'));
  const bounceNote = expectingBounce
    ? 'A corrective retrace is expected before the next directional leg completes.'
    : null;

  // Detect potential W1/WC ambiguity (low confidence, corrective structure)
  const isAmbiguous = !isMultiDegree && probability < 0.55
    && (structure?.toLowerCase().includes('corrective') || waveLabel === '1' || waveLabel === 'A');
  const ambiguityNote = isAmbiguous
    ? `Note: Wave 1 and Wave A (start of correction) look identical at this stage — probability is below 55%, so both scenarios are viable.`
    : null;

  // Trigger level: closest fib to current price
  const triggerLevel = nextTarget ?? (invalidation ?? null);

  const prompt = `You are an institutional Elliott Wave analyst. Write exactly 3 sentences for a professional swing trader. Be specific — cite exact dollar prices, name the trigger level, and state what to watch for. No disclaimers.

Situation:
- Ticker: ${ticker}
- Current price: ${price ? `$${price.toFixed(2)}` : 'unknown'} ${waveMoveText}
- Primary count: Wave ${waveLabel} (${structure}) — ${Math.round(probability * 100)}% Bayesian confidence
- Wave stage: ${stageNote}
- Wave structure type: ${waveType ?? 'impulse'}
${htfContext ? htfContext : ''}
${bounceNote ? `- ${bounceNote}` : ''}
${altText ? `- ${altText}` : ''}
${ambiguityNote ? `- ${ambiguityNote}` : ''}
- Market regime: ${regime ?? 'unknown'}
- GEX regime: ${gexLevel ?? 'neutral'}
- Fibonacci targets: ${targetsText}
- Invalidation / stop: ${invalidation ? `$${invalidation.toFixed(2)}` : 'none computed'}
- Key Fibonacci levels: ${fibText}
- Next trigger level: ${triggerLevel ? `$${triggerLevel.toFixed(2)}` : 'none'}

${isMultiDegree
  ? `Sentences:
1. Explain how ${ticker}'s Wave ${waveLabel} fits within the ${htfTF} Wave ${htfLabel} structure and what this degree alignment means for near-term direction.
2. Name the most actionable price level — the specific trigger that confirms the next leg — and the nearest Fibonacci target if that level holds.
3. State the precise invalidation price and the one thing to watch before taking a position.`
  : `Sentences:
1. Describe what ${ticker} Wave ${waveLabel} means right now at $${price?.toFixed(2) ?? '?'}, including ${expectingBounce ? 'the corrective bounce setup and where it likely ends' : 'what typically follows this position in the count'}.
2. State the specific trigger price to watch — the level that confirms the next leg — and the nearest Fibonacci target.
3. Name the exact invalidation level${isAmbiguous ? ', address the W1 vs Wave A ambiguity' : ''}, and state what the alternate scenario implies for direction.`}

Use present tense. No disclaimers. Every sentence must name at least one specific price.`;

  try {
    const anthropicRes = await fetch(ANTHROPIC_API_URL, {
      method: 'POST',
      headers: {
        'x-api-key':         apiKey,
        'anthropic-version': '2023-06-01',
        'content-type':      'application/json',
      },
      body: JSON.stringify({
        model:      'claude-sonnet-4-20250514',
        max_tokens: 320,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!anthropicRes.ok) {
      const errText = await anthropicRes.text();
      return new Response(
        JSON.stringify({ error: 'Anthropic API error', detail: errText }),
        { status: 502, headers: { 'Content-Type': 'application/json' } },
      );
    }

    interface AnthropicContent { type: string; text: string }
    interface AnthropicResponse { content: AnthropicContent[] }
    const data = await anthropicRes.json() as AnthropicResponse;
    const commentary = data.content?.[0]?.text?.trim() ?? '';

    return new Response(JSON.stringify({ commentary }), {
      status: 200,
      headers: {
        'Content-Type':                'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: 'Internal error', detail: String(err) }),
      { status: 500, headers: { 'Content-Type': 'application/json' } },
    );
  }
}
