/**
 * services/proxy/ai-commentary.ts — Vercel Edge Function
 *
 * POST /api/ai-commentary
 *
 * Accepts wave scenario context from the mobile client and returns a natural
 * language interpretation generated by claude-sonnet-4-20250514.
 *
 * The ANTHROPIC_API_KEY environment variable is server-side only — never
 * exposed in the client bundle.
 *
 * Request body:
 *   { ticker, waveLabel, structure, probability, fibLevels, regime,
 *     nextTarget, invalidation, price, gexLevel }
 *
 * Response:
 *   { commentary: string }
 */

export const config = { runtime: 'edge' };

interface CommentaryRequest {
  ticker:       string;
  waveLabel:    string;
  structure:    string;
  probability:  number;
  fibLevels?:   { label: string; price: number }[];
  regime?:      string;
  nextTarget?:  number | null;
  invalidation?: number | null;
  price?:       number | null;
  gexLevel?:    string | null;
}

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';

export default async function handler(req: Request): Promise<Response> {
  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }

  const apiKey = process.env['ANTHROPIC_API_KEY'];
  if (!apiKey) {
    return new Response(JSON.stringify({ error: 'AI commentary not configured' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  let body: CommentaryRequest;
  try {
    body = await req.json() as CommentaryRequest;
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  const {
    ticker, waveLabel, structure, probability,
    fibLevels, regime, nextTarget, invalidation, price, gexLevel,
  } = body;

  const fibText = fibLevels && fibLevels.length > 0
    ? fibLevels.map((f) => `${f.label} at $${f.price.toFixed(2)}`).join(', ')
    : 'no Fibonacci levels computed';

  const prompt = `You are an institutional Elliott Wave analyst providing a concise trade scenario interpretation.

Context:
- Ticker: ${ticker}
- Current price: ${price ? `$${price.toFixed(2)}` : 'unknown'}
- Active wave: Wave ${waveLabel} (${structure})
- Bayesian probability: ${Math.round(probability * 100)}%
- Market regime: ${regime ?? 'unknown'}
- GEX level: ${gexLevel ?? 'neutral'}
- Key Fibonacci levels: ${fibText}
- Primary target: ${nextTarget ? `$${nextTarget.toFixed(2)}` : 'none computed'}
- Invalidation: ${invalidation ? `$${invalidation.toFixed(2)}` : 'none computed'}

Write 2–3 sentences of plain-English commentary for a professional trader:
1. Explain what Wave ${waveLabel} means for the current price action in ${ticker}.
2. Reference the most relevant Fibonacci level and the GEX regime.
3. Give a specific, actionable interpretation (what to watch for, where the trade breaks down).

Be concise, specific, and avoid generic disclaimers. Write in present tense.`;

  try {
    const anthropicRes = await fetch(ANTHROPIC_API_URL, {
      method: 'POST',
      headers: {
        'x-api-key':         apiKey,
        'anthropic-version': '2023-06-01',
        'content-type':      'application/json',
      },
      body: JSON.stringify({
        model:      'claude-sonnet-4-20250514',
        max_tokens: 256,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!anthropicRes.ok) {
      const errText = await anthropicRes.text();
      return new Response(
        JSON.stringify({ error: 'Anthropic API error', detail: errText }),
        { status: 502, headers: { 'Content-Type': 'application/json' } },
      );
    }

    interface AnthropicContent { type: string; text: string }
    interface AnthropicResponse { content: AnthropicContent[] }
    const data = await anthropicRes.json() as AnthropicResponse;
    const commentary = data.content?.[0]?.text?.trim() ?? '';

    return new Response(JSON.stringify({ commentary }), {
      status: 200,
      headers: {
        'Content-Type':                'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: 'Internal error', detail: String(err) }),
      { status: 500, headers: { 'Content-Type': 'application/json' } },
    );
  }
}
