/**
 * services/proxy/api/ai-commentary.ts — Vercel Serverless Function
 *
 * POST /api/ai-commentary
 *
 * Accepts wave scenario context from the mobile client and returns a natural
 * language interpretation generated by claude-sonnet-4-20250514.
 *
 * The ANTHROPIC_API_KEY environment variable is server-side only — never
 * exposed in the client bundle.
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';

interface CommentaryRequest {
  ticker:        string;
  waveLabel:     string;
  structure:     string;
  probability:   number;
  fibLevels?:    { label: string; price: number }[];
  regime?:       string;
  nextTarget?:   number | null;
  invalidation?: number | null;
  price?:        number | null;
  gexLevel?:     string | null;
}

const ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method Not Allowed' });

  const apiKey = process.env['ANTHROPIC_API_KEY'];
  if (!apiKey) {
    return res.status(503).json({ error: 'AI commentary not configured' });
  }

  const body = req.body as CommentaryRequest;
  if (!body || !body.ticker) {
    return res.status(400).json({ error: 'Invalid request body' });
  }

  const {
    ticker, waveLabel, structure, probability,
    fibLevels, regime, nextTarget, invalidation, price, gexLevel,
  } = body;

  const fibText = fibLevels && fibLevels.length > 0
    ? fibLevels.map((f) => `${f.label} at $${f.price.toFixed(2)}`).join(', ')
    : 'no Fibonacci levels computed';

  const prompt = `You are an institutional Elliott Wave analyst providing a concise trade scenario interpretation.

Context:
- Ticker: ${ticker}
- Current price: ${price ? `$${price.toFixed(2)}` : 'unknown'}
- Active wave: Wave ${waveLabel} (${structure})
- Bayesian probability: ${Math.round(probability * 100)}%
- Market regime: ${regime ?? 'unknown'}
- GEX level: ${gexLevel ?? 'neutral'}
- Key Fibonacci levels: ${fibText}
- Primary target: ${nextTarget ? `$${nextTarget.toFixed(2)}` : 'none computed'}
- Invalidation: ${invalidation ? `$${invalidation.toFixed(2)}` : 'none computed'}

Write 2–3 sentences of plain-English commentary for a professional trader:
1. Explain what Wave ${waveLabel} means for the current price action in ${ticker}.
2. Reference the most relevant Fibonacci level and the GEX regime.
3. Give a specific, actionable interpretation (what to watch for, where the trade breaks down).

Be concise, specific, and avoid generic disclaimers. Write in present tense.`;

  try {
    const anthropicRes = await fetch(ANTHROPIC_API_URL, {
      method: 'POST',
      headers: {
        'x-api-key':         apiKey,
        'anthropic-version': '2023-06-01',
        'content-type':      'application/json',
      },
      body: JSON.stringify({
        model:      'claude-sonnet-4-20250514',
        max_tokens: 256,
        messages:   [{ role: 'user', content: prompt }],
      }),
    });

    if (!anthropicRes.ok) {
      const errText = await anthropicRes.text();
      return res.status(502).json({ error: 'Anthropic API error', detail: errText });
    }

    interface AnthropicContent { type: string; text: string }
    interface AnthropicResponse { content: AnthropicContent[] }
    const data = await anthropicRes.json() as AnthropicResponse;
    const commentary = data.content?.[0]?.text?.trim() ?? '';
    return res.status(200).json({ commentary });
  } catch (err) {
    return res.status(500).json({ error: 'Internal error', detail: String(err) });
  }
}
